services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    command: [
      "./manage.py",
      "runserver_plus", "0.0.0.0:8000"
    ]
    # Log printing is enhanced by a TTY
    tty: true
    working_dir: /home/vscode/net-maestro
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/home/vscode/net-maestro
      - ${ROSS_PATH:-../ross}:/home/vscode/ross
      - pkg_cache:/home/vscode/pkg-cache
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    command: [
      "uv", "run",
      "celery",
      "--app", "net_maestro.celery",
      "worker",
      "--loglevel", "INFO",
      "--without-mingle",
      "--without-heartbeat",
      "--without-gossip"
    ]
    # uv progress doesn't display properly with a Docker TTY
    tty: false
    working_dir: /home/vscode/net-maestro
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/home/vscode/net-maestro
      - ${ROSS_PATH:-../ross}:/home/vscode/ross
      - pkg_cache:/home/vscode/pkg-cache
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  pkg_cache:
