# Generated by Django 6.0.2 on 2026-02-19 20:11
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("file", s3_file_field.fields.S3FileField()),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.run"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_lp", models.FloatField()),
                ("dest_lp", models.FloatField()),
                ("time_step", models.IntegerField()),
                ("event_type", models.FloatField()),
                ("virtual_send", models.FloatField()),
                ("virtual_receive", models.FloatField()),
                (
                    "event_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.eventfile"
                    ),
                ),
            ],
        ),
    ]
