# Generated by Django 6.0.2 on 2026-02-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventfile_eventrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='run',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_files',
                to='core.run',
            ),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='event_file',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='core.eventfile',
            ),
        ),
    ]
