# Generated by Django 6.0.2 on 2026-02-20 20:30
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_eventfile_eventrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
