# Generated by Django 6.0.2 on 2026-02-24 18:51
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_run_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("file", s3_file_field.fields.S3FileField()),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.run"),
                ),
            ],
        ),
    ]
