# Generated by Django 6.0.2 on 2026-03-20 14:38
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_simulation_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("file", s3_file_field.fields.S3FileField()),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.run"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lp_id", models.IntegerField()),
                ("component_id", models.IntegerField()),
                ("virtual_time", models.FloatField()),
                ("real_time", models.FloatField()),
                ("send_count", models.IntegerField()),
                ("send_bytes", models.BigIntegerField()),
                ("send_time", models.FloatField()),
                ("receive_count", models.IntegerField()),
                ("receive_bytes", models.BigIntegerField()),
                ("receive_time", models.FloatField()),
                (
                    "model_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.modelfile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationKpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("PE_ID", models.IntegerField()),
                ("events_processed", models.IntegerField()),
                ("events_rolled_back", models.IntegerField()),
                ("network_sends", models.IntegerField()),
                ("network_reads", models.IntegerField()),
                ("efficiency", models.FloatField()),
                ("virtual_time", models.FloatField()),
                ("real_time", models.FloatField()),
                ("KP_ID", models.IntegerField()),
                ("events_abort", models.IntegerField()),
                ("total_rollbacks", models.IntegerField()),
                ("secondary_rollbacks", models.IntegerField()),
                ("time_ahead_gvt", models.FloatField()),
                (
                    "simulation_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kp_records",
                        to="core.simulationfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimulationLpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("PE_ID", models.IntegerField()),
                ("events_processed", models.IntegerField()),
                ("events_rolled_back", models.IntegerField()),
                ("network_sends", models.IntegerField()),
                ("network_reads", models.IntegerField()),
                ("efficiency", models.FloatField()),
                ("virtual_time", models.FloatField()),
                ("real_time", models.FloatField()),
                ("KP_ID", models.IntegerField()),
                ("LP_ID", models.IntegerField()),
                ("events_abort", models.IntegerField()),
                (
                    "simulation_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lp_records",
                        to="core.simulationfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimulationPeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("PE_ID", models.IntegerField()),
                ("events_processed", models.IntegerField()),
                ("events_rolled_back", models.IntegerField()),
                ("network_sends", models.IntegerField()),
                ("network_reads", models.IntegerField()),
                ("efficiency", models.FloatField()),
                ("virtual_time", models.FloatField()),
                ("real_time", models.FloatField()),
                ("events_aborted", models.IntegerField()),
                ("total_rollbacks", models.IntegerField()),
                ("secondary_rollbacks", models.IntegerField()),
                ("fossil_collection_attempts", models.IntegerField()),
                ("pq_queue_size", models.IntegerField()),
                ("number_gvt", models.IntegerField()),
                ("pe_event_ties", models.IntegerField()),
                ("all_reduce", models.IntegerField()),
                ("network_read_time", models.FloatField()),
                ("network_other_time", models.FloatField()),
                ("gvt_time", models.FloatField()),
                ("fossil_collect_time", models.FloatField()),
                ("event_abort_time", models.FloatField()),
                ("event_process_time", models.FloatField()),
                ("pq_time", models.FloatField()),
                ("rollback_time", models.FloatField()),
                ("cancel_q_time", models.FloatField()),
                ("avl_time", models.FloatField()),
                ("buddy_time", models.FloatField()),
                ("lz4_time", models.FloatField()),
                (
                    "simulation_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pe_records",
                        to="core.simulationfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
