# Generated by Django 6.0.2 on 2026-03-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_simultion_pe_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationKpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE_ID', models.IntegerField()),
                ('KP_ID', models.IntegerField()),
                ('events_processed', models.IntegerField()),
                ('events_abort', models.IntegerField()),
                ('events_rolled_back', models.IntegerField()),
                ('total_rollbacks', models.IntegerField()),
                ('secondary_rollbacks', models.IntegerField()),
                ('network_sends', models.IntegerField()),
                ('network_reads', models.IntegerField()),
                ('time_ahead_gvt', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('virtual_time', models.FloatField()),
                ('real_time', models.FloatField()),
                ('simulation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulationfile')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE_ID', models.IntegerField()),
                ('KP_ID', models.IntegerField()),
                ('LP_ID', models.IntegerField()),
                ('events_processed', models.IntegerField()),
                ('events_abort', models.IntegerField()),
                ('events_rolled_back', models.IntegerField()),
                ('network_sends', models.IntegerField()),
                ('network_reads', models.IntegerField()),
                ('efficiency', models.FloatField()),
                ('virtual_time', models.FloatField()),
                ('real_time', models.FloatField()),
                ('simulation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulationfile')),
            ],
        ),
    ]
