# Generated by Django 6.0.2 on 2026-03-24 19:37
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_simulation_kp_and_lp_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("file", s3_file_field.fields.S3FileField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_files",
                        to="core.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lp_id", models.IntegerField()),
                ("component_id", models.IntegerField()),
                ("virtual_time", models.FloatField()),
                ("real_time", models.FloatField()),
                ("send_count", models.IntegerField()),
                ("send_bytes", models.BigIntegerField()),
                ("send_time", models.FloatField()),
                ("receive_count", models.IntegerField()),
                ("receive_bytes", models.BigIntegerField()),
                ("receive_time", models.FloatField()),
                (
                    "model_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_records",
                        to="core.modelfile",
                    ),
                ),
            ],
        ),
    ]
