# Generated by Django 6.0 on 2026-04-29 19:54

from __future__ import annotations

from pathlib import Path

from django.db import migrations

from net_maestro.core.constants import RunStatus
from net_maestro.core.parsers.event_trace_file import EventFileParser
from net_maestro.core.parsers.model_file import ModelFileParser
from net_maestro.core.parsers.ross_binary_file import ROSSFile


def seed_example_data(apps, schema_editor):
    """Seed the database with example data from the data/ directory."""
    Run = apps.get_model("core", "Run")
    EventFile = apps.get_model("core", "EventFile")
    EventRecord = apps.get_model("core", "EventRecord")
    ModelFile = apps.get_model("core", "ModelFile")
    ModelRecord = apps.get_model("core", "ModelRecord")
    SimulationFile = apps.get_model("core", "SimulationFile")
    SimulationPeRecord = apps.get_model("core", "SimulationPeRecord")
    SimulationKpRecord = apps.get_model("core", "SimulationKpRecord")
    SimulationLpRecord = apps.get_model("core", "SimulationLpRecord")

    # Check if example data already exists
    if Run.objects.filter(name="Example Completed Run").exists():
        return

    # Get the base directory
    base_dir = Path(__file__).resolve().parent.parent.parent.parent

    # Create a single run with status COMPLETED
    run = Run.objects.create(
        name="Example Completed Run",
        description="Auto-seeded from data/ directory.",
        status=RunStatus.COMPLETED,
    )

    # Paths to example data files
    event_file_path = base_dir / "data" / "events" / "esnet-model-inst-evtrace.bin"
    model_file_path = base_dir / "data" / "models" / "esnet-model-inst-analysis-lps.bin"
    simulation_file_path = base_dir / "data" / "simulations" / "ross-stats-gvt.bin"

    # Parse and ingest event data
    event_file = EventFile.objects.create(run=run)
    event_parser = EventFileParser(event_file_path)
    event_parser.read()

    event_records = [
        EventRecord(
            event_file=event_file,
            source_lp=float(record["source_lp"]),
            dest_lp=float(record["dest_lp"]),
            time_step=int(record["time_step"]),
            event_type=float(record["event_type"]),
            virtual_send=float(record["virtual_send"]),
            virtual_receive=float(record["virtual_receive"]),
        )
        for record in event_parser.parse_event_records()
    ]
    EventRecord.objects.bulk_create(event_records)

    # Parse and ingest model data
    model_file = ModelFile.objects.create(run=run)
    model_parser = ModelFileParser(model_file_path)
    model_parser.read()

    model_records = [
        ModelRecord(
            model_file=model_file,
            lp_id=int(record["lp_id"]),
            component_id=int(record["component_id"]),
            virtual_time=float(record["virtual_time"]),
            real_time=float(record["real_time"]),
            send_count=int(record["send_count"]),
            send_bytes=int(record["send_bytes"]),
            send_time=float(record["send_time"]),
            receive_count=int(record["receive_count"]),
            receive_bytes=int(record["receive_bytes"]),
            receive_time=float(record["receive_time"]),
        )
        for record in model_parser.parse_model_records()
    ]
    ModelRecord.objects.bulk_create(model_records)

    # Parse and ingest simulation data
    simulation_file = SimulationFile.objects.create(run=run)
    ross_parser = ROSSFile(simulation_file_path)
    ross_parser.read()

    pe_records = []
    kp_records = []
    lp_records = []

    for record_type, record_data in ross_parser.parse_simulation_records():
        if record_type.value == "pe":
            pe_records.append(
                SimulationPeRecord(
                    simulation_file=simulation_file,
                    PE_ID=int(record_data["PE_ID"]),
                    events_processed=int(record_data["events_processed"]),
                    events_rolled_back=int(record_data["events_rolled_back"]),
                    network_sends=int(record_data["network_sends"]),
                    network_reads=int(record_data["network_reads"]),
                    efficiency=float(record_data["efficiency"]),
                    virtual_time=float(record_data["virtual_time"]),
                    real_time=float(record_data["real_time"]),
                    events_aborted=int(record_data["events_aborted"]),
                    total_rollbacks=int(record_data["total_rollbacks"]),
                    secondary_rollbacks=int(record_data["secondary_rollbacks"]),
                    fossil_collection_attempts=int(record_data["fossil_collection_attempts"]),
                    pq_queue_size=int(record_data["pq_queue_size"]),
                    number_gvt=int(record_data["number_gvt"]),
                    pe_event_ties=int(record_data["pe_event_ties"]),
                    all_reduce=int(record_data["all_reduce"]),
                    network_read_time=float(record_data["network_read_time"]),
                    network_other_time=float(record_data["network_other_time"]),
                    gvt_time=float(record_data["gvt_time"]),
                    fossil_collect_time=float(record_data["fossil_collect_time"]),
                    event_abort_time=float(record_data["event_abort_time"]),
                    event_process_time=float(record_data["event_process_time"]),
                    pq_time=float(record_data["pq_time"]),
                    rollback_time=float(record_data["rollback_time"]),
                    cancel_q_time=float(record_data["cancel_q_time"]),
                    avl_time=float(record_data["avl_time"]),
                    buddy_time=float(record_data["buddy_time"]),
                    lz4_time=float(record_data["lz4_time"]),
                )
            )
        elif record_type.value == "kp":
            kp_records.append(
                SimulationKpRecord(
                    simulation_file=simulation_file,
                    PE_ID=int(record_data["PE_ID"]),
                    events_processed=int(record_data["events_processed"]),
                    events_rolled_back=int(record_data["events_rolled_back"]),
                    network_sends=int(record_data["network_sends"]),
                    network_reads=int(record_data["network_reads"]),
                    efficiency=float(record_data["efficiency"]),
                    virtual_time=float(record_data["virtual_time"]),
                    real_time=float(record_data["real_time"]),
                    KP_ID=int(record_data["KP_ID"]),
                    events_abort=int(record_data["events_abort"]),
                    total_rollbacks=int(record_data["total_rollbacks"]),
                    secondary_rollbacks=int(record_data["secondary_rollbacks"]),
                    time_ahead_gvt=float(record_data["time_ahead_gvt"]),
                )
            )
        elif record_type.value == "lp":
            lp_records.append(
                SimulationLpRecord(
                    simulation_file=simulation_file,
                    PE_ID=int(record_data["PE_ID"]),
                    events_processed=int(record_data["events_processed"]),
                    events_rolled_back=int(record_data["events_rolled_back"]),
                    network_sends=int(record_data["network_sends"]),
                    network_reads=int(record_data["network_reads"]),
                    efficiency=float(record_data["efficiency"]),
                    virtual_time=float(record_data["virtual_time"]),
                    real_time=float(record_data["real_time"]),
                    KP_ID=int(record_data["KP_ID"]),
                    LP_ID=int(record_data["LP_ID"]),
                    events_abort=int(record_data["events_abort"]),
                )
            )

    SimulationPeRecord.objects.bulk_create(pe_records)
    SimulationKpRecord.objects.bulk_create(kp_records)
    SimulationLpRecord.objects.bulk_create(lp_records)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_modelfile_modelrecord"),
    ]

    operations = [
        migrations.RunPython(seed_example_data, migrations.RunPython.noop),
    ]
