# Generated by Django 6.0.2 on 2026-04-02 15:51
from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_modelfile_modelrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("modelnet_simplep2p", "Modelnet Simplep2P"),
                            ("synthetic_workload", "Synthetic Workload"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="eventfile",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_files",
                to="core.run",
            ),
        ),
        migrations.AlterField(
            model_name="eventrecord",
            name="event_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_records",
                to="core.eventfile",
            ),
        ),
        migrations.CreateModel(
            name="HostConfig",
            fields=[
                (
                    "componentconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.componentconfig",
                    ),
                ),
                ("traffic", models.CharField(choices=[("uniform", "Uniform")], max_length=255)),
                (
                    "num_messages",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "arrival_time",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "payload_size",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
            ],
            bases=("core.componentconfig",),
        ),
        migrations.CreateModel(
            name="RouterConfig",
            fields=[
                (
                    "componentconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.componentconfig",
                    ),
                ),
            ],
            bases=("core.componentconfig",),
        ),
        migrations.CreateModel(
            name="SwitchConfig",
            fields=[
                (
                    "componentconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.componentconfig",
                    ),
                ),
            ],
            bases=("core.componentconfig",),
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("host", "Host"), ("router", "Router"), ("switch", "Switch")],
                        max_length=255,
                    ),
                ),
                (
                    "ingress_bandwidth",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "egress_bandwidth",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "ingress_latency",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "egress_latency",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.componentconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topologies",
                        to="core.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="core.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_links",
                        to="core.node",
                    ),
                ),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_links",
                        to="core.topology",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="node",
            name="topology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="core.topology",
            ),
        ),
        migrations.AddField(
            model_name="componentconfig",
            name="topology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_configs",
                to="core.topology",
            ),
        ),
        migrations.AddConstraint(
            model_name="topology",
            constraint=models.UniqueConstraint(fields=("run",), name="one_topology_per_run"),
        ),
        migrations.AddConstraint(
            model_name="nodelink",
            constraint=models.UniqueConstraint(
                fields=("topology", "source", "target"), name="unique_link_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="nodelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="no_self_links",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("topology", "name"), name="unique_node_name_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentconfig",
            constraint=models.UniqueConstraint(
                fields=("topology", "model"), name="unique_config_per_model_per_topology"
            ),
        ),
    ]
