# Generated by Django 6.0.4 on 2026-04-28 16:08
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_modelfile_modelrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
