# Generated by Django 6.0.5 on 2026-06-11 21:25
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_modelfile_modelrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHOLDSimulationLpRecord",
            fields=[
                (
                    "simulationlprecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.simulationlprecord",
                    ),
                ),
                ("s_process_event", models.IntegerField()),
            ],
            options={
                "verbose_name": "PHOLD Simulation LP Record",
                "verbose_name_plural": "PHOLD Simulation LP Records",
            },
            bases=("core.simulationlprecord",),
        ),
    ]
