# Generated by Django 6.0.4 on 2026-04-28 16:14
from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_topology"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("modelnet_simplep2p", "Modelnet Simplep2P"),
                            ("simplep2p", "Simplep2P"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("host", "Host"), ("router", "Router"), ("switch", "Switch")],
                        max_length=255,
                    ),
                ),
                (
                    "ingress_bandwidth",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "egress_bandwidth",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "ingress_latency",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "egress_latency",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.topology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="core.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_links",
                        to="core.node",
                    ),
                ),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_links",
                        to="core.topology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostNode",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.node",
                    ),
                ),
                ("traffic", models.CharField(choices=[("uniform", "Uniform")], max_length=255)),
                (
                    "num_messages",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "arrival_time",
                    models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
                ),
                (
                    "payload_size",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
            ],
            bases=("core.node",),
        ),
        migrations.CreateModel(
            name="RouterNode",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.node",
                    ),
                ),
            ],
            bases=("core.node",),
        ),
        migrations.CreateModel(
            name="SwitchNode",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.node",
                    ),
                ),
            ],
            bases=("core.node",),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("topology", "name"), name="unique_node_name_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="nodelink",
            constraint=models.UniqueConstraint(
                fields=("topology", "source", "target"), name="unique_link_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="nodelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="no_self_links",
            ),
        ),
    ]
