# Generated by Django 6.0.6 on 2026-08-12 16:22
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_pholdsimulationlprecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("host", "Host"), ("router", "Router"), ("switch", "Switch")],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("engine", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
