# Generated by Django 6.0.6 on 2026-08-19 14:24
from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_component_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "Saved"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="saved",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PHOLDSimulationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "synch",
                    models.IntegerField(
                        choices=[
                            (1, "Sequential"),
                            (2, "Conservative"),
                            (3, "Optimistic"),
                            (4, "Optimistic Debug"),
                            (5, "Optimistic Realtime"),
                            (6, "Reverse Handler Check"),
                        ],
                        default=3,
                        verbose_name="Synchronization protocol",
                    ),
                ),
                (
                    "avl_size",
                    models.IntegerField(
                        default=18,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="AVL tree size",
                    ),
                ),
                (
                    "nlp",
                    models.IntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="LPs per processor",
                    ),
                ),
                (
                    "remote",
                    models.FloatField(
                        default=0.25,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Remote event rate",
                    ),
                ),
                (
                    "mean",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Mean timestamp",
                    ),
                ),
                (
                    "mult",
                    models.FloatField(
                        default=1.4,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                        verbose_name="Memory multiplier",
                    ),
                ),
                (
                    "lookahead",
                    models.FloatField(
                        default=1.0, validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                (
                    "start_events",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Start events per LP",
                    ),
                ),
                (
                    "memory",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Additional memory buffers",
                    ),
                ),
                ("stagger", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phold_configs",
                        to="core.run",
                    ),
                ),
            ],
        ),
    ]
