# Generated by Django 6.0.6 on 2026-07-14 22:48
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_run_status_pholdsimulationconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pholdsimulationconfig",
            name="lookahead",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
