# Generated by Django 6.0.6 on 2026-09-11 13:55

from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_pholdsimulationconfig_lookahead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="TopologyNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "node_kind",
                    models.CharField(
                        choices=[("switch", "Switch"), ("terminal", "Terminal")],
                        default="switch",
                        max_length=100,
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "terminals",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Attached terminals",
                    ),
                ),
                (
                    "terminal_bandwidth",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Terminal bandwidth (bits/s)",
                    ),
                ),
                (
                    "switch_buffer",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Switch buffer (bits)",
                    ),
                ),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.topology",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="TopologyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bandwidth",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Bandwidth (bits/s)",
                    ),
                ),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.topology",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="core.topologynode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="core.topologynode",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.UniqueConstraint(
                fields=("topology", "name"), name="unique_node_name_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.UniqueConstraint(
                fields=("topology", "order_index"), name="unique_node_order_index_per_topology"
            ),
        ),
        migrations.AddConstraint(
            model_name="topologylink",
            constraint=models.UniqueConstraint(
                fields=("topology", "source_node", "target_node"), name="unique_link_per_topology"
            ),
        ),
    ]
