# Generated by Django 6.0.6 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pholdsimulationconfig_lookahead'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='simulation_type',
            field=models.CharField(choices=[('esnet', 'ESnet'), ('phold', 'PHOLD'), ('ffw', 'FFW')], default='esnet', max_length=32),
        ),
    ]
