# Generated by Django 6.0.6 on 2026-09-21 18:39

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_pholdsimulationconfig_lookahead"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentmodel",
            name="base_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="componentmodel",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("host", "Host"),
                    ("router", "Router"),
                    ("switch", "Switch"),
                    ("terminal", "Terminal"),
                ],
                max_length=100,
            ),
        ),
    ]
