# Generated by Django 6.0.6 on 2026-09-11 15:11

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_topology_topologynode_topologylink_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="topologylink",
            constraint=models.CheckConstraint(
                condition=models.Q(("bandwidth__gte", 0)), name="link_bandwidth_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_index__gte", 0)), name="node_order_index_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("terminals__isnull", True), ("terminals__gte", 0), _connector="OR"
                ),
                name="node_terminals_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("terminal_bandwidth__isnull", True),
                    ("terminal_bandwidth__gte", 0),
                    _connector="OR",
                ),
                name="node_terminal_bandwidth_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="topologynode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("switch_buffer__isnull", True), ("switch_buffer__gte", 0), _connector="OR"
                ),
                name="node_switch_buffer_non_negative",
            ),
        ),
    ]
