# Generated by Django 6.0.6 on 2026-09-25 13:32

from __future__ import annotations

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_add_ffw_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="FFWSimulationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topology_name", models.CharField(max_length=200, verbose_name="Topology")),
                (
                    "traffic",
                    models.CharField(
                        choices=[("random", "Random"), ("trace", "Trace replay")],
                        default="random",
                        max_length=20,
                    ),
                ),
                (
                    "np",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="MPI processes",
                    ),
                ),
                (
                    "sync",
                    models.IntegerField(
                        choices=[
                            (1, "Sequential"),
                            (2, "Conservative"),
                            (3, "Optimistic"),
                            (4, "Optimistic Debug"),
                            (5, "Optimistic Realtime"),
                            (6, "Reverse Handler Check"),
                        ],
                        default=1,
                        verbose_name="Synchronization protocol",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ffw_configs",
                        to="core.run",
                    ),
                ),
            ],
        ),
    ]
