# Generated by Django 6.0.6 on 2026-09-27 17:41

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_componentmodel_base_model_and_more"),
        ("core", "0015_ffwsimulationconfig"),
    ]

    operations = []
