services:
  django:
    # Don't auto-run the default command, launch.json or the terminal will be used.
    command: !reset []

  celery:
    # Celery will be started via launch.json or the terminal.
    profiles: ["celery"]
